package settings

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/iameter/collector/internal/fsutil"
	"github.com/iameter/collector/internal/platform"
)

const statusLineKey = "statusLine"

// InstallConfig is everything Install needs, all explicit paths so tests
// don't touch the real home directory.
type InstallConfig struct {
	SettingsPath   string // path to Claude Code's settings.json
	BackupPath     string // pristine pre-IAMETER snapshot
	ChainStatePath string // where a preserved third-party statusLine is stored
	IAMeterCommand string // BuildCommand(absolute iameter binary path)
}

// Action describes what Install did, for the human-readable install report
// (section 32).
type Action string

const (
	ActionInstalled Action = "installed" // no prior statusLine
	ActionChained   Action = "chained"   // preserved a third-party statusLine
	ActionUpdated   Action = "updated"   // already IA METER, path refreshed
	ActionUnchanged Action = "unchanged" // already IA METER, nothing to do
)

type InstallResult struct {
	Action      Action
	ChainedFrom *StatusLineEntry // set only when Action == ActionChained
}

// Install makes IA METER the configured statusLine, preserving and
// chaining any pre-existing third-party statusLine (section 13). It is
// idempotent: running it again with the same IAMeterCommand is a no-op:
// ActionUnchanged.
func Install(cfg InstallConfig) (InstallResult, error) {
	if err := ensureParentDir(cfg.SettingsPath); err != nil {
		return InstallResult{}, err
	}
	if err := backupIfAbsent(cfg.SettingsPath, cfg.BackupPath); err != nil {
		return InstallResult{}, err
	}

	doc, err := load(cfg.SettingsPath)
	if err != nil {
		return InstallResult{}, err
	}

	existing, hasExisting, err := readStatusLine(doc)
	if err != nil {
		return InstallResult{}, err
	}

	result := InstallResult{}
	switch {
	case !hasExisting:
		result.Action = ActionInstalled

	case isIAMeterCommand(existing.Command):
		if existing.Command == cfg.IAMeterCommand {
			result.Action = ActionUnchanged
			return result, nil // nothing to write at all
		}
		result.Action = ActionUpdated

	default:
		// A third-party statusLine is configured. Preserve it so
		// cmdStatusline can chain to it, and never overwrite a
		// previously-saved chain state with something we're about to
		// replace anyway — but here we ARE about to replace it, and this
		// path only runs when the current entry isn't ours, so this is
		// exactly the entry to save.
		if err := saveChainState(cfg.ChainStatePath, existing); err != nil {
			return InstallResult{}, err
		}
		result.Action = ActionChained
		result.ChainedFrom = existing
	}

	newEntry := StatusLineEntry{Type: "command", Command: cfg.IAMeterCommand}
	entryBytes, err := json.Marshal(newEntry)
	if err != nil {
		return InstallResult{}, fmt.Errorf("settings: marshal statusLine: %w", err)
	}
	doc[statusLineKey] = entryBytes

	if err := save(cfg.SettingsPath, doc); err != nil {
		return InstallResult{}, err
	}
	return result, nil
}

func readStatusLine(doc raw) (*StatusLineEntry, bool, error) {
	rawEntry, ok := doc[statusLineKey]
	if !ok || string(rawEntry) == "null" {
		return nil, false, nil
	}
	var entry StatusLineEntry
	if err := json.Unmarshal(rawEntry, &entry); err != nil {
		return nil, false, fmt.Errorf("settings: existing statusLine is not the expected shape: %w", err)
	}
	return &entry, true, nil
}

// isIAMeterCommand reports whether a statusLine command string was
// generated by IA METER's own installer, without requiring an exact byte
// match against the current binary path (which may have moved). It guards
// against recursion: re-running install must never chain IA METER to
// itself.
func isIAMeterCommand(command string) bool {
	trimmed := strings.TrimSpace(command)
	return strings.Contains(trimmed, platform.BinaryName()) && strings.HasSuffix(trimmed, "statusline")
}

// IsIAMeterCommand reports whether a statusLine command string was
// generated by IA METER's installer. Exported for `iameter doctor`.
func IsIAMeterCommand(command string) bool { return isIAMeterCommand(command) }

// CurrentStatusLine reads settingsPath and returns its statusLine entry,
// if any, without modifying anything. Exported for `iameter doctor`/
// `iameter status` introspection.
func CurrentStatusLine(settingsPath string) (*StatusLineEntry, bool, error) {
	doc, err := load(settingsPath)
	if err != nil {
		return nil, false, err
	}
	return readStatusLine(doc)
}

func saveChainState(path string, entry *StatusLineEntry) error {
	data, err := json.MarshalIndent(entry, "", "  ")
	if err != nil {
		return fmt.Errorf("settings: marshal chain state: %w", err)
	}
	return fsutil.AtomicWriteFile(path, data, 0o600)
}

// LoadChainState returns the preserved third-party statusLine entry, if
// any. Used by `iameter statusline` at runtime to decide whether to chain.
func LoadChainState(path string) (*StatusLineEntry, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("settings: read chain state: %w", err)
	}
	var entry StatusLineEntry
	if err := json.Unmarshal(data, &entry); err != nil {
		return nil, fmt.Errorf("settings: parse chain state: %w", err)
	}
	return &entry, nil
}

func ensureParentDir(settingsPath string) error {
	return os.MkdirAll(filepath.Dir(settingsPath), 0o700)
}
